<a href="https://colab.research.google.com/github/ugnature/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question what is going on in this notebook u can come on git hub: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## introductions to Tensors

### Creating tensors

Pytorch tensors are creating using `torch.tensor()` => https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python integer
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[4,5]])
MATRIX

tensor([[7, 8],
        [4, 5]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[[1,2,4],
                        [3,45,6],
                        [4,6,7]],[[1,2,4],
                                  [3,45,6],
                                  [4,6,7]],[[1,2,4],
                                            [3,45,6],
                                            [4,6,7]],[[1,2,4],
                                                      [3,45,6],
                                                      [4,6,7]]],[[[1,2,4],
                                                                  [3,45,6],
                                                                   [4,6,7]],[[1,2,4],
                                                                             [3,45,6],
                                                                             [4,6,7]],[[1,2,4],
                                                                                       [3,45,6],
                                                                                      [4,6,7]],[[1,2,4],
                                                                                                 [3,45,6],
                                                                                                [4,6,7]]]])
TENSOR

tensor([[[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]],


        [[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]]])

In [14]:
TENSOR.ndim

4

In [15]:
TENSOR.shape

torch.Size([2, 4, 3, 3])

In [16]:
TENSOR[1]

tensor([[[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]]])

### Rendom Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with the tensor full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors -> https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand

In [17]:
# Create a random tensos of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9510, 0.1481, 0.3799, 0.1494],
        [0.5082, 0.6451, 0.1835, 0.7864],
        [0.4792, 0.0513, 0.3582, 0.7929]])

In [18]:
# number of dimension
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # size=(height, width, color_channels(R, G, B))
random_image_size_tensor, 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
# Creata a tensor of all zeros

zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of Ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a arange of tensors and tensors-like

In [23]:
# Use torch.arange()
five_to_forty = torch.arange(5,40)
five_to_forty

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the big 3 big errors, you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Precision in computing -> https://en.wikipedia.org/wiki/Precision_(computer_science)

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is the tensor (e.g. float32 or float16 , int32 etc.)
                                                device=None, # what device is your tensor on
                                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
# zero dimension tensor is called scalar
scalar = torch.tensor(3.14)

In [30]:
# see this result below, it is zero dimension
scalar.ndim

0

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = float_16_tensor.type(torch.LongTensor)
int_32_tensor

tensor([3, 6, 9])

In [33]:
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype -> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -> to get shape/size from a tensor, `tensor.shape`
3. Tensors not on right device -> to get device from a tensor(e.g. CPU , GPU or TPU), can use `tensor.device` 

In [34]:
# Create a tensor
some_tensor = torch.rand(4,5, dtype=torch.float16)
some_tensor

tensor([[0.8911, 0.9727, 0.2612, 0.4185, 0.0845],
        [0.9351, 0.3843, 0.9980, 0.0874, 0.0449],
        [0.9502, 0.5132, 0.1616, 0.4678, 0.4185],
        [0.7271, 0.1685, 0.3579, 0.3721, 0.0273]], dtype=torch.float16)

In [35]:
# Find of details about some_tensor
# datatype, shape, device
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}, And shape of Tensor: {some_tensor.shape}, at last the device is on: {some_tensor.device}")

tensor([[0.8911, 0.9727, 0.2612, 0.4185, 0.0845],
        [0.9351, 0.3843, 0.9980, 0.0874, 0.0449],
        [0.9502, 0.5132, 0.1616, 0.4678, 0.4185],
        [0.7271, 0.1685, 0.3579, 0.3721, 0.0273]], dtype=torch.float16)
Datatype of tensor: torch.float16, And shape of Tensor: torch.Size([4, 5]), at last the device is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multipication (element-wise)
* Division
* Matrix multipication

In [36]:
# Create a tensor and than add 10 to it
tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [38]:
# Substract 10 in tensor
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [39]:
# devide the tensor by 10
tensor = (tensor / 10)
tensor = tensor.type(torch.int32)
tensor

tensor([10, 11, 12], dtype=torch.int32)

In [40]:
# try out PyTorch in-built functions
torch.mul(tensor, 10), torch.sub(tensor, 67), torch.div(tensor, 34), torch.add(tensor, 345)

(tensor([100, 110, 120], dtype=torch.int32),
 tensor([-57, -56, -55], dtype=torch.int32),
 tensor([0.2941, 0.3235, 0.3529]),
 tensor([355, 356, 357], dtype=torch.int32))

### Matrix Multipication

Two main ways of performing multipication in neural networks and deep learning:

1. Element-wise multipication
2. Matrix Multipication(dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

More information on multiplying matrices - http://matrixmultiplication.xyz/

There are two main rules that performing matrix multipication needs to satisfy: 

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` => resulting shape `(2, 2)`
* `(3, 2) @ (2, 3)` => resulting shape `(3, 3)`

In [41]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[1.2416, 0.3564],
        [0.7751, 0.1618]])

In [42]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)), torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

(tensor([[0.1006, 0.1816, 0.3568],
         [0.4282, 0.5541, 1.0125],
         [0.2939, 0.3512, 0.6277]]),
 torch.Size([3, 3]))

In [43]:
# Element wise multipication
print(tensor, "*", tensor)
print("----------------------------")
print(f"Equals: {tensor * tensor}")

tensor([10, 11, 12], dtype=torch.int32) * tensor([10, 11, 12], dtype=torch.int32)
----------------------------
Equals: tensor([100, 121, 144], dtype=torch.int32)


In [44]:
# Matrix Multipication
torch.matmul(tensor, tensor)

tensor(365, dtype=torch.int32)

In [45]:
tensor

tensor([10, 11, 12], dtype=torch.int32)

In [46]:
tensor @ tensor

tensor(365, dtype=torch.int32)

In [47]:
# Matrix Multipication by hand

# reason-> we are combining two matrix -- in this case these two are two tensor [10,11,12], [10,11,12] 

# Matrix multipication: 

10*10  +  11*11  +  12*12 

# output:  365

365

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(365, dtype=torch.int32)
CPU times: user 582 µs, sys: 0 ns, total: 582 µs
Wall time: 542 µs


In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 72 µs, sys: 0 ns, total: 72 µs
Wall time: 77.7 µs


tensor(365, dtype=torch.int32)

### One of the most common errors in deep learning: shape errors

In [51]:
# Shapes for matrix multipication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [4, 5]])

tensor_B = torch.tensor([[5, 6],
                         [7, 9],
                         [3, 6]])

torch.mm(tensor_A, tensor_B) # torch.mm is short version of torch.matmul

RuntimeError: ignored

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [53]:
print(f"Original Tensor: {tensor_B}"),
print(f"Original Tensor shape: {tensor_A.shape}, {tensor_B.shape}"),
print("\n---------------------------")
print("\nnow after using transpose(T) on tensor_B and the manipulated result is:")
print(f"Manipulated Tensor shape: {tensor_A.shape}, {tensor_B.T.shape}"),
tensor_B.T

Original Tensor: tensor([[5, 6],
        [7, 9],
        [3, 6]])
Original Tensor shape: torch.Size([3, 2]), torch.Size([3, 2])

---------------------------

now after using transpose(T) on tensor_B and the manipulated result is:
Manipulated Tensor shape: torch.Size([3, 2]), torch.Size([2, 3])


tensor([[5, 7, 3],
        [6, 9, 6]])

In [54]:
print("Now it works after transposing one of the tensor <- cause inner dimension must match" )
output = torch.mm(tensor_A, tensor_B.T) 
print("Output:\n")
print(output)
print(f"\nOutput shape: {output.shape}")

Now it works after transposing one of the tensor <- cause inner dimension must match
Output:

tensor([[17, 25, 15],
        [39, 57, 33],
        [50, 73, 42]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [55]:
# Create a tensor
x = torch.arange(1, 100, 10) # 0 to 100 with the step of 10
x, x.type

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), <function Tensor.type>)

In [56]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [57]:
# Find the max
torch.max(x), 

(tensor(91),)

In [58]:
# Find the mean - note: torch.mean() function requires a tensor of float32 or complex datatype
torch.mean(x.type(torch.float32)), x.type(torch.complex64).mean()

(tensor(46.), tensor(46.+0.j))

In [59]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [60]:
# to get the positional arguments like on which index is the max value or min value
print(f"Tensor: {x}")
print(f"MAX POSITIONAL VALUE at index: {x.argmax()}")
print(f"MIN POSITIONAL VALUE at index: {x.argmin()}")
print(f"index on 9, element: {x[9]}")

Tensor: tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
MAX POSITIONAL VALUE at index: 9
MIN POSITIONAL VALUE at index: 0
index on 9, element: 91


## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return of view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way 

In [79]:
# Let's create a tensor
import torch
x = torch.arange(1., 16.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]),
 torch.Size([15]))

In [86]:
# LET'S START RESHAPING
# reshape only work if that value is like z = x * y, meaning value 15 can be the result of 5 * 3 or 3 * 5
# than this reshaped tensor can be created of ([5, 3]) or ([3, 5])
# let's add an extra dimention
print(f"total elements: {x}")
print("\n--------------------------------")
x_reshaped = x.reshape(1, 15)
print("\n--------------------------------")
x_reshaped, x_reshaped.shape


total elements: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

--------------------------------

--------------------------------


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15.]]),
 torch.Size([1, 15]))

In [85]:
# LET'S CHANGE THE VIEW
z = x.view(1, 15)
z, z.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15.]]),
 torch.Size([1, 15]))

In [88]:
# Changing z change x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
# we target the 0 index and changed the value with value 5 and now the value in x also have changed cause z was sharing the same memory
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]))

In [101]:
# Stack tensors on top of each other
# dim=0 -> stack vertical
# dim=1 -> stack horizontal
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked, x.shape, x.ndim

(tensor([[ 5.,  5.,  5.],
         [ 2.,  2.,  2.],
         [ 3.,  3.,  3.],
         [ 4.,  4.,  4.],
         [ 5.,  5.,  5.],
         [ 6.,  6.,  6.],
         [ 7.,  7.,  7.],
         [ 8.,  8.,  8.],
         [ 9.,  9.,  9.],
         [10., 10., 10.],
         [11., 11., 11.],
         [12., 12., 12.],
         [13., 13., 13.],
         [14., 14., 14.],
         [15., 15., 15.]]),
 torch.Size([15]),
 1)

In [134]:
# torch.squeeze() - which removes all single dimensions from the target tensor
print(f"previous tensor: {x_reshaped}")
print(f"\nprevious tensor shape/size: {x_reshaped.shape}")
print("-----------------------------------------")

# remove extra dimension from x_reshaped 
print("\ntensor after squeezed-> there was 2 bracket now there is only one")
x_squeezed = x_reshaped.squeeze()
print(f"squeezed new tensor: {x_squeezed}")
print(f"\nnew tensor shape: {x_squeezed.shape}")

previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]])

previous tensor shape/size: torch.Size([1, 15])
-----------------------------------------

tensor after squeezed-> there was 2 bracket now there is only one
squeezed new tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

new tensor shape: torch.Size([15])


In [136]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous Target: {x_squeezed}")
print(f"\nPrevious Tensor size: {x_squeezed.shape}")
print("-----------------------------------------")

# add extra dimension with unsqueeze
print("\nNow unsqueezed tensor method will add new dimension to the previous tensor")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New Unsqueezed Tensor: {x_unsqueezed}")
print(f"New Tensor shape: {x_unsqueezed.shape}")

Previous Target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15.])

Previous Tensor size: torch.Size([15])
-----------------------------------------

Now unsqueezed tensor method will add new dimension to the previous tensor
New Unsqueezed Tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]])
New Tensor shape: torch.Size([1, 15])


In [168]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# create a tensor
x = torch.rand(size=(224, 224, 3)) # [height, width, colour_channel]
print("meaning this tensor is going to contain 3 values in 1st dimension and these 2 tensors in 2nd dimesion under 5 tensors of 3rd dimensions")
print(f"This is the current tensor look like:\n {x}")
print(f"\ncurrent tensor shape: {x.shape}\n")

# now let's permute the tensor
print("now we want 5 values in 2 tensor of 2nd dimension under 3 tensors of 3rd dimensions")
# to permute we have to work with the index
x_permuted = torch.permute(x, (2, 1, 0)) # [coulor_channels, width, height]
print(f"Permuted tensor:\n {x_permuted}")
print(f"\nPermuted tensor size: {x_permuted.shape}")

meaning this tensor is going to contain 3 values in 1st dimension and these 2 tensors in 2nd dimesion under 5 tensors of 3rd dimensions
This is the current tensor look like:
 tensor([[[0.2072, 0.2287, 0.8068],
         [0.0801, 0.3870, 0.7646],
         [0.1411, 0.3077, 0.5139],
         ...,
         [0.8978, 0.2058, 0.6039],
         [0.2573, 0.9819, 0.6248],
         [0.3023, 0.0164, 0.9707]],

        [[0.2567, 0.3263, 0.4002],
         [0.8101, 0.5848, 0.3259],
         [0.9792, 0.8255, 0.0180],
         ...,
         [0.7586, 0.8411, 0.6495],
         [0.9160, 0.2775, 0.6959],
         [0.5641, 0.0138, 0.6092]],

        [[0.6734, 0.9425, 0.4193],
         [0.5891, 0.3998, 0.4468],
         [0.8372, 0.2434, 0.5856],
         ...,
         [0.2490, 0.4737, 0.7275],
         [0.0014, 0.8881, 0.9350],
         [0.9975, 0.7524, 0.8278]],

        ...,

        [[0.8152, 0.8580, 0.1881],
         [0.2091, 0.8157, 0.0833],
         [0.5571, 0.1319, 0.0178],
         ...,
         [0.53

In [193]:
# change value in x tensor

x[0, 0, 0]= 552
x[0, 0, 0], x_permuted[0, 0, 0]

(tensor(552.), tensor(552.))

## Indexing (selecting data from indexing)

Indexing with PyTorch is similar to indexing with numPy.

In [200]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [201]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [216]:
# Let's index on the middle bracker (dim =1)
x[0][1]

tensor([4, 5, 6])

In [208]:
# let's enter in the first dimension of the x tenson and get the values based on dim=1 index
x[0][0][2]

tensor(3)

In [217]:
# this value we can get in other way also, whichever you like
# let's try to get value 9 from the tensor
x[0, 2 ,2]

tensor(9)

In [227]:
# You can also use ":" to select all values or tensor from a target dimension

x[:, 1]


tensor([[4, 5, 6]])

In [235]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension

x[:, 0 :, 1]

tensor([[2, 5, 8]])

In [243]:
# get all the values of the 0 dimensions but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [245]:
# get index 0 of 0th and 1st dimension all values on 2nd index of inner dimension

x[0, 0, :]

tensor([1, 2, 3])

In [257]:
# Index on x to return 9
x[0, 2, 2]

# Index on x to return 3, 6, 9
x[:, :, 2,]

tensor([[3, 6, 9]])

## PyTorch Tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.tensor.numpy()`

In [260]:
# NumPy array to tensor
import torch
import numpy as np

# cause we want to go to from np array to tansor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [266]:
# default numpy data is float64 so keep this in mind! okay..
array.dtype

# so if we want to keep the datatype of float32 than we can do this
tensor32 = torch.from_numpy(array).type(torch.float32)
tensor32, tensor32.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [263]:
# however PyTorch default datatype is float32
torch.arange(1.0, 8.0).dtype

torch.float32

In [268]:
# Change the value of array, the question is : what will this do to `tensor`?
array = array + 1
# answer: tensor doesn't change cause tensor is located into new memory not sharing the same memory of numpy
array, tensor32

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [278]:
## Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [283]:
# Change the Tensor, the question is: what happen to numpy_tensor?

tensor = tensor + 1
# answer: numpy doesn't change cause this is also using a new space in the memory not sharing the same
tensor, numpy_tensor

(tensor([6., 6., 6., 6., 6., 6., 6.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibity (trying to take random out of random)

In short how a neural network learns:

`start with random number -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [292]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.8556, 0.4802, 0.3992, 0.7195],
        [0.2396, 0.9465, 0.0433, 0.6189],
        [0.1116, 0.9231, 0.8363, 0.4801]])
tensor([[0.4507, 0.8604, 0.4584, 0.4794],
        [0.1431, 0.3545, 0.0527, 0.7922],
        [0.6419, 0.9942, 0.5793, 0.9952]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [298]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 108 # i choose 108 because because it's the code of the universe :)

# remember we need to use seed every time whenever we are creating a new tensor of same seed 
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
print(random_tensor_C)
print("-----------------------")

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_D)

print("-----------------------")
print(random_tensor_C == random_tensor_D)


tensor([[0.8044, 0.2480, 0.8032, 0.5651],
        [0.5028, 0.6326, 0.0533, 0.4508],
        [0.6778, 0.4901, 0.0208, 0.2987]])
-----------------------
tensor([[0.8044, 0.2480, 0.8032, 0.5651],
        [0.5028, 0.6326, 0.0533, 0.4508],
        [0.6778, 0.4901, 0.0208, 0.2987]])
-----------------------
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2nd and 3rd option -> PyTorch + GPU drivers which is CUDA takes a little bit of setting up, to do this refer to PyTorch setup documentation:
https://pytorch.org/get-started/locally/


In [1]:
!nvidia-smi

Sat Jun 10 09:41:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practive to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [11]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [12]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors back to the CPU

In [13]:
# if tensor is on GPU, can't transform to NumPy

tensor_on_gpu.numpy()

TypeError: ignored

In [14]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [16]:
tensor_on_gpu # remain unchanged

tensor([1, 2, 3], device='cuda:0')