<a href="https://colab.research.google.com/github/ugnature/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question what is going on in this notebook u can come on git hub: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## introductions to Tensors

### Creating tensors

Pytorch tensors are creating using `torch.tensor()` => https://pytorch.org/docs/stable/tensors.html

In [11]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [14]:
# Get tensor back as python integer
scalar.item()

7

In [15]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
MATRIX = torch.tensor([[7,8],[4,5]])
MATRIX

tensor([[7, 8],
        [4, 5]])

In [19]:
MATRIX.ndim

2

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
MATRIX[0]

tensor([7, 8])

In [46]:
# TENSOR
TENSOR = torch.tensor([[[[1,2,4],
                        [3,45,6],
                        [4,6,7]],[[1,2,4],
                                  [3,45,6],
                                  [4,6,7]],[[1,2,4],
                                            [3,45,6],
                                            [4,6,7]],[[1,2,4],
                                                      [3,45,6],
                                                      [4,6,7]]],[[[1,2,4],
                                                                  [3,45,6],
                                                                   [4,6,7]],[[1,2,4],
                                                                             [3,45,6],
                                                                             [4,6,7]],[[1,2,4],
                                                                                       [3,45,6],
                                                                                      [4,6,7]],[[1,2,4],
                                                                                                 [3,45,6],
                                                                                                [4,6,7]]]])
TENSOR

tensor([[[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]],


        [[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]]])

In [47]:
TENSOR.ndim

4

In [48]:
TENSOR.shape

torch.Size([2, 4, 3, 3])

In [50]:
TENSOR[1]

tensor([[[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]]])

### Rendom Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with the tensor full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
### Random Tensors
