<a href="https://colab.research.google.com/github/ugnature/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question what is going on in this notebook u can come on git hub: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## introductions to Tensors

### Creating tensors

Pytorch tensors are creating using `torch.tensor()` => https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python integer
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],[4,5]])
MATRIX

tensor([[7, 8],
        [4, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[[1,2,4],
                        [3,45,6],
                        [4,6,7]],[[1,2,4],
                                  [3,45,6],
                                  [4,6,7]],[[1,2,4],
                                            [3,45,6],
                                            [4,6,7]],[[1,2,4],
                                                      [3,45,6],
                                                      [4,6,7]]],[[[1,2,4],
                                                                  [3,45,6],
                                                                   [4,6,7]],[[1,2,4],
                                                                             [3,45,6],
                                                                             [4,6,7]],[[1,2,4],
                                                                                       [3,45,6],
                                                                                      [4,6,7]],[[1,2,4],
                                                                                                 [3,45,6],
                                                                                                [4,6,7]]]])
TENSOR

tensor([[[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]],


        [[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]]])

In [13]:
TENSOR.ndim

4

In [14]:
TENSOR.shape

torch.Size([2, 4, 3, 3])

In [15]:
TENSOR[1]

tensor([[[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]]])

### Rendom Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with the tensor full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors -> https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand

In [16]:
# Create a random tensos of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3962, 0.6099, 0.0612, 0.2854],
        [0.7884, 0.4444, 0.7250, 0.1928],
        [0.7690, 0.9214, 0.3921, 0.0413]])

In [17]:
# number of dimension
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # size=(height, width, color_channels(R, G, B))
random_image_size_tensor, 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [19]:
# Creata a tensor of all zeros

zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of Ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a arange of tensors and tensors-like

In [22]:
# Use torch.arange()
five_to_forty = torch.arange(5,40)
five_to_forty

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the big 3 big errors, you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Precision in computing -> https://en.wikipedia.org/wiki/Precision_(computer_science)

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is the tensor (e.g. float32 or float16 , int32 etc.)
                                                device=None, # what device is your tensor on
                                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float16

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
# zero dimension tensor is called scalar
scalar = torch.tensor(3.14)

In [39]:
# see this result below, it is zero dimension
scalar.ndim

0

In [40]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [45]:
int_32_tensor = float_16_tensor.type(torch.LongTensor)
int_32_tensor

tensor([3, 6, 9])

In [46]:
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype -> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -> to get shape/size from a tensor, `tensor.shape`
3. Tensors not on right device -> to get device from a tensor(e.g. CPU , GPU or TPU), can use `tensor.device` 

In [63]:
# Create a tensor
some_tensor = torch.rand(4,5, dtype=torch.float16)
some_tensor

tensor([[0.1465, 0.1592, 0.8618, 0.1040, 0.5669],
        [0.5776, 0.5645, 0.4390, 0.5752, 0.2866],
        [0.4009, 0.5840, 0.8286, 0.2520, 0.3101],
        [0.5732, 0.4751, 0.9219, 0.7832, 0.8105]], dtype=torch.float16)

In [57]:
# Find of details about some_tensor
# datatype, shape, device
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}, And shape of Tensor: {some_tensor.shape}, at last the device is on: {some_tensor.device}")

tensor([[0.0020, 0.4951, 0.8638, 0.0020, 0.3159],
        [0.2866, 0.0898, 0.9893, 0.6543, 0.4717],
        [0.0527, 0.7969, 0.8232, 0.4810, 0.7896],
        [0.0142, 0.4111, 0.8491, 0.0342, 0.2256]], dtype=torch.float16)
Datatype of tensor: torch.float16, And shape of Tensor: torch.Size([4, 5]), at last the device is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multipication (element-wise)
* Division
* Matrix multipication

In [66]:
# Create a tensor and than add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])