<a href="https://colab.research.google.com/github/ugnature/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question what is going on in this notebook u can come on git hub: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## introductions to Tensors

### Creating tensors

Pytorch tensors are creating using `torch.tensor()` => https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python integer
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],[4,5]])
MATRIX

tensor([[7, 8],
        [4, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[[1,2,4],
                        [3,45,6],
                        [4,6,7]],[[1,2,4],
                                  [3,45,6],
                                  [4,6,7]],[[1,2,4],
                                            [3,45,6],
                                            [4,6,7]],[[1,2,4],
                                                      [3,45,6],
                                                      [4,6,7]]],[[[1,2,4],
                                                                  [3,45,6],
                                                                   [4,6,7]],[[1,2,4],
                                                                             [3,45,6],
                                                                             [4,6,7]],[[1,2,4],
                                                                                       [3,45,6],
                                                                                      [4,6,7]],[[1,2,4],
                                                                                                 [3,45,6],
                                                                                                [4,6,7]]]])
TENSOR

tensor([[[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]],


        [[[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]],

         [[ 1,  2,  4],
          [ 3, 45,  6],
          [ 4,  6,  7]]]])

In [13]:
TENSOR.ndim

4

In [14]:
TENSOR.shape

torch.Size([2, 4, 3, 3])

In [15]:
TENSOR[1]

tensor([[[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]],

        [[ 1,  2,  4],
         [ 3, 45,  6],
         [ 4,  6,  7]]])

### Rendom Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with the tensor full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors -> https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand

In [16]:
# Create a random tensos of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8972, 0.5611, 0.3910, 0.9443],
        [0.3609, 0.5128, 0.5480, 0.3490],
        [0.2743, 0.9133, 0.9309, 0.5830]])

In [17]:
# number of dimension
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # size=(height, width, color_channels(R, G, B))
random_image_size_tensor, 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [19]:
# Creata a tensor of all zeros

zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of Ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a arange of tensors and tensors-like

In [22]:
# Use torch.arange()
five_to_forty = torch.arange(5,40)
five_to_forty

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the big 3 big errors, you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Precision in computing -> https://en.wikipedia.org/wiki/Precision_(computer_science)

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is the tensor (e.g. float32 or float16 , int32 etc.)
                                                device=None, # what device is your tensor on
                                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
# zero dimension tensor is called scalar
scalar = torch.tensor(3.14)

In [29]:
# see this result below, it is zero dimension
scalar.ndim

0

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = float_16_tensor.type(torch.LongTensor)
int_32_tensor

tensor([3, 6, 9])

In [32]:
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype -> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape -> to get shape/size from a tensor, `tensor.shape`
3. Tensors not on right device -> to get device from a tensor(e.g. CPU , GPU or TPU), can use `tensor.device` 

In [33]:
# Create a tensor
some_tensor = torch.rand(4,5, dtype=torch.float16)
some_tensor

tensor([[0.9146, 0.8926, 0.5659, 0.7090, 0.2715],
        [0.0215, 0.3872, 0.3887, 0.2251, 0.1392],
        [0.9922, 0.7656, 0.1411, 0.0420, 0.6162],
        [0.2305, 0.2393, 0.4341, 0.6602, 0.6543]], dtype=torch.float16)

In [34]:
# Find of details about some_tensor
# datatype, shape, device
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}, And shape of Tensor: {some_tensor.shape}, at last the device is on: {some_tensor.device}")

tensor([[0.9146, 0.8926, 0.5659, 0.7090, 0.2715],
        [0.0215, 0.3872, 0.3887, 0.2251, 0.1392],
        [0.9922, 0.7656, 0.1411, 0.0420, 0.6162],
        [0.2305, 0.2393, 0.4341, 0.6602, 0.6543]], dtype=torch.float16)
Datatype of tensor: torch.float16, And shape of Tensor: torch.Size([4, 5]), at last the device is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multipication (element-wise)
* Division
* Matrix multipication

In [35]:
# Create a tensor and than add 10 to it
tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [37]:
# Substract 10 in tensor
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [38]:
# devide the tensor by 10
tensor = (tensor / 10)
tensor = tensor.type(torch.int32)
tensor

tensor([10, 11, 12], dtype=torch.int32)

In [39]:
# try out PyTorch in-built functions
torch.mul(tensor, 10), torch.sub(tensor, 67), torch.div(tensor, 34), torch.add(tensor, 345)

(tensor([100, 110, 120], dtype=torch.int32),
 tensor([-57, -56, -55], dtype=torch.int32),
 tensor([0.2941, 0.3235, 0.3529]),
 tensor([355, 356, 357], dtype=torch.int32))

### Matrix Multipication

Two main ways of performing multipication in neural networks and deep learning:

1. Element-wise multipication
2. Matrix Multipication(dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

More information on multiplying matrices - http://matrixmultiplication.xyz/

There are two main rules that performing matrix multipication needs to satisfy: 

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` => resulting shape `(2, 2)`
* `(3, 2) @ (2, 3)` => resulting shape `(3, 3)`

In [40]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.5965, 0.6286],
        [0.4224, 0.6732]])

In [41]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)), torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

(tensor([[0.8252, 0.9850, 0.1173],
         [0.9630, 1.0659, 0.1351],
         [0.2832, 0.2685, 0.0387]]),
 torch.Size([3, 3]))

In [42]:
# Element wise multipication
print(tensor, "*", tensor)
print("----------------------------")
print(f"Equals: {tensor * tensor}")

tensor([10, 11, 12], dtype=torch.int32) * tensor([10, 11, 12], dtype=torch.int32)
----------------------------
Equals: tensor([100, 121, 144], dtype=torch.int32)


In [43]:
# Matrix Multipication
torch.matmul(tensor, tensor)

tensor(365, dtype=torch.int32)

In [44]:
tensor

tensor([10, 11, 12], dtype=torch.int32)

In [45]:
tensor @ tensor

tensor(365, dtype=torch.int32)

In [46]:
# Matrix Multipication by hand

# reason-> we are combining two matrix -- in this case these two are two tensor [10,11,12], [10,11,12] 

# Matrix multipication: 

10*10  +  11*11  +  12*12 

# output:  365

365

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(365, dtype=torch.int32)
CPU times: user 421 µs, sys: 0 ns, total: 421 µs
Wall time: 427 µs


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 27 µs, sys: 4 µs, total: 31 µs
Wall time: 33.9 µs


tensor(365, dtype=torch.int32)

### One of the most common errors in deep learning: shape errors

In [49]:
# Shapes for matrix multipication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [4, 5]])

tensor_B = torch.tensor([[5, 6],
                         [7, 9],
                         [3, 6]])

torch.mm(tensor_A, tensor_B) # torch.mm is short version of torch.matmul

RuntimeError: ignored

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [52]:
print(f"Original Tensor: {tensor_B}"),
print(f"Original Tensor shape: {tensor_A.shape}, {tensor_B.shape}"),
print("\n---------------------------")
print("\nnow after using transpose(T) on tensor_B and the manipulated result is:")
print(f"Manipulated Tensor shape: {tensor_A.shape}, {tensor_B.T.shape}"),
tensor_B.T

Original Tensor: tensor([[5, 6],
        [7, 9],
        [3, 6]])
Original Tensor shape: torch.Size([3, 2]), torch.Size([3, 2])

---------------------------

now after using transpose(T) on tensor_B and the manipulated result is:
Manipulated Tensor shape: torch.Size([3, 2]), torch.Size([2, 3])


tensor([[5, 7, 3],
        [6, 9, 6]])

In [53]:
print("Now it works after transposing one of the tensor <- cause inner dimension must match" )
output = torch.mm(tensor_A, tensor_B.T) 
print("Output:\n")
print(output)
print(f"\nOutput shape: {output.shape}")

Now it works after transposing one of the tensor <- cause inner dimension must match
Output:

tensor([[17, 25, 15],
        [39, 57, 33],
        [50, 73, 42]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [54]:
# Create a tensor
x = torch.arange(1, 100, 10) # 0 to 100 with the step of 10
x, x.type

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), <function Tensor.type>)

In [55]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
# Find the max
torch.max(x), 

(tensor(91),)

In [57]:
# Find the mean - note: torch.mean() function requires a tensor of float32 or complex datatype
torch.mean(x.type(torch.float32)), x.type(torch.complex64).mean()

(tensor(46.), tensor(46.+0.j))

In [58]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [61]:
# to get the positional arguments like on which index is the max value or min value
print(f"Tensor: {x}")
print(f"MAX POSITIONAL VALUE at index: {x.argmax()}")
print(f"MIN POSITIONAL VALUE at index: {x.argmin()}")
print(f"index on 9, element: {x[9]}")

Tensor: tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
MAX POSITIONAL VALUE at index: 9
MIN POSITIONAL VALUE at index: 0
index on 9, element: 91


## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return of view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
